# Generated by Django 3.1 on 2020-08-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_token',
            new_name='token',
        ),
    ]
