# Generated by Django 3.1 on 2020-08-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_clothe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clothes', to='users.user'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='users.user'),
        ),
        migrations.AddField(
            model_name='like',
            name='clothe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.category'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
