# Generated by Django 3.1 on 2020-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20200826_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AddField(
            model_name='clothes',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
