# Generated by Django 3.1 on 2020-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20200828_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('UNISEX', 'UNISEX')], max_length=8),
        ),
    ]
