# Generated by Django 3.1 on 2020-08-28 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0005_auto_20200828_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL),
        ),
    ]
